/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.registration.model.impl;

import com.amf.registration.model.AMFUser;
import com.amf.registration.model.AMFUserModel;
import com.amf.registration.model.AMFUserSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AMFUser service. Represents a row in the &quot;AMFUser_AMFUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AMFUserModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AMFUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AMFUserImpl
 * @generated
 */
@JSON(strict = true)
public class AMFUserModelImpl
	extends BaseModelImpl<AMFUser> implements AMFUserModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a amf user model instance should use the <code>AMFUser</code> interface instead.
	 */
	public static final String TABLE_NAME = "AMFUser_AMFUser";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"amfUserId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"firstName", Types.VARCHAR}, {"lastName", Types.VARCHAR},
		{"emailAddress", Types.VARCHAR}, {"gender", Types.VARCHAR},
		{"birthDay", Types.VARCHAR}, {"birthMonth", Types.VARCHAR},
		{"birthYear", Types.VARCHAR}, {"password_", Types.VARCHAR},
		{"confirmedPassword", Types.VARCHAR}, {"homePhone", Types.VARCHAR},
		{"mobilePhone", Types.VARCHAR}, {"address", Types.VARCHAR},
		{"address2", Types.VARCHAR}, {"city", Types.VARCHAR},
		{"state_", Types.VARCHAR}, {"zip", Types.VARCHAR},
		{"securityQuestion", Types.VARCHAR}, {"securityAnswer", Types.VARCHAR},
		{"acceptedTou", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("amfUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("emailAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("gender", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("birthDay", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("birthMonth", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("birthYear", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("password_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("confirmedPassword", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("homePhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mobilePhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("city", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("state_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("zip", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("securityQuestion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("securityAnswer", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("acceptedTou", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AMFUser_AMFUser (uuid_ VARCHAR(75) null,amfUserId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,firstName VARCHAR(75) null,lastName VARCHAR(75) null,emailAddress VARCHAR(75) null,gender VARCHAR(75) null,birthDay VARCHAR(75) null,birthMonth VARCHAR(75) null,birthYear VARCHAR(75) null,password_ VARCHAR(75) null,confirmedPassword VARCHAR(75) null,homePhone VARCHAR(75) null,mobilePhone VARCHAR(75) null,address VARCHAR(75) null,address2 VARCHAR(75) null,city VARCHAR(75) null,state_ VARCHAR(75) null,zip VARCHAR(75) null,securityQuestion VARCHAR(75) null,securityAnswer VARCHAR(75) null,acceptedTou VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table AMFUser_AMFUser";

	public static final String ORDER_BY_JPQL =
		" ORDER BY amfUser.firstName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AMFUser_AMFUser.firstName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long FIRSTNAME_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static AMFUser toModel(AMFUserSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AMFUser model = new AMFUserImpl();

		model.setUuid(soapModel.getUuid());
		model.setAmfUserId(soapModel.getAmfUserId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setFirstName(soapModel.getFirstName());
		model.setLastName(soapModel.getLastName());
		model.setEmailAddress(soapModel.getEmailAddress());
		model.setGender(soapModel.getGender());
		model.setBirthDay(soapModel.getBirthDay());
		model.setBirthMonth(soapModel.getBirthMonth());
		model.setBirthYear(soapModel.getBirthYear());
		model.setPassword(soapModel.getPassword());
		model.setConfirmedPassword(soapModel.getConfirmedPassword());
		model.setHomePhone(soapModel.getHomePhone());
		model.setMobilePhone(soapModel.getMobilePhone());
		model.setAddress(soapModel.getAddress());
		model.setAddress2(soapModel.getAddress2());
		model.setCity(soapModel.getCity());
		model.setState(soapModel.getState());
		model.setZip(soapModel.getZip());
		model.setSecurityQuestion(soapModel.getSecurityQuestion());
		model.setSecurityAnswer(soapModel.getSecurityAnswer());
		model.setAcceptedTou(soapModel.getAcceptedTou());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<AMFUser> toModels(AMFUserSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AMFUser> models = new ArrayList<AMFUser>(soapModels.length);

		for (AMFUserSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public AMFUserModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _amfUserId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAmfUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _amfUserId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AMFUser.class;
	}

	@Override
	public String getModelClassName() {
		return AMFUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AMFUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AMFUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AMFUser, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((AMFUser)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AMFUser, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AMFUser, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AMFUser)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AMFUser, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AMFUser, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AMFUser>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AMFUser.class.getClassLoader(), AMFUser.class, ModelWrapper.class);

		try {
			Constructor<AMFUser> constructor =
				(Constructor<AMFUser>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<AMFUser, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AMFUser, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AMFUser, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<AMFUser, Object>>();
		Map<String, BiConsumer<AMFUser, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<AMFUser, ?>>();

		attributeGetterFunctions.put("uuid", AMFUser::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<AMFUser, String>)AMFUser::setUuid);
		attributeGetterFunctions.put("amfUserId", AMFUser::getAmfUserId);
		attributeSetterBiConsumers.put(
			"amfUserId", (BiConsumer<AMFUser, Long>)AMFUser::setAmfUserId);
		attributeGetterFunctions.put("groupId", AMFUser::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<AMFUser, Long>)AMFUser::setGroupId);
		attributeGetterFunctions.put("companyId", AMFUser::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<AMFUser, Long>)AMFUser::setCompanyId);
		attributeGetterFunctions.put("userId", AMFUser::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<AMFUser, Long>)AMFUser::setUserId);
		attributeGetterFunctions.put("userName", AMFUser::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<AMFUser, String>)AMFUser::setUserName);
		attributeGetterFunctions.put("createDate", AMFUser::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<AMFUser, Date>)AMFUser::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", AMFUser::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<AMFUser, Date>)AMFUser::setModifiedDate);
		attributeGetterFunctions.put("firstName", AMFUser::getFirstName);
		attributeSetterBiConsumers.put(
			"firstName", (BiConsumer<AMFUser, String>)AMFUser::setFirstName);
		attributeGetterFunctions.put("lastName", AMFUser::getLastName);
		attributeSetterBiConsumers.put(
			"lastName", (BiConsumer<AMFUser, String>)AMFUser::setLastName);
		attributeGetterFunctions.put("emailAddress", AMFUser::getEmailAddress);
		attributeSetterBiConsumers.put(
			"emailAddress",
			(BiConsumer<AMFUser, String>)AMFUser::setEmailAddress);
		attributeGetterFunctions.put("gender", AMFUser::getGender);
		attributeSetterBiConsumers.put(
			"gender", (BiConsumer<AMFUser, String>)AMFUser::setGender);
		attributeGetterFunctions.put("birthDay", AMFUser::getBirthDay);
		attributeSetterBiConsumers.put(
			"birthDay", (BiConsumer<AMFUser, String>)AMFUser::setBirthDay);
		attributeGetterFunctions.put("birthMonth", AMFUser::getBirthMonth);
		attributeSetterBiConsumers.put(
			"birthMonth", (BiConsumer<AMFUser, String>)AMFUser::setBirthMonth);
		attributeGetterFunctions.put("birthYear", AMFUser::getBirthYear);
		attributeSetterBiConsumers.put(
			"birthYear", (BiConsumer<AMFUser, String>)AMFUser::setBirthYear);
		attributeGetterFunctions.put("password", AMFUser::getPassword);
		attributeSetterBiConsumers.put(
			"password", (BiConsumer<AMFUser, String>)AMFUser::setPassword);
		attributeGetterFunctions.put(
			"confirmedPassword", AMFUser::getConfirmedPassword);
		attributeSetterBiConsumers.put(
			"confirmedPassword",
			(BiConsumer<AMFUser, String>)AMFUser::setConfirmedPassword);
		attributeGetterFunctions.put("homePhone", AMFUser::getHomePhone);
		attributeSetterBiConsumers.put(
			"homePhone", (BiConsumer<AMFUser, String>)AMFUser::setHomePhone);
		attributeGetterFunctions.put("mobilePhone", AMFUser::getMobilePhone);
		attributeSetterBiConsumers.put(
			"mobilePhone",
			(BiConsumer<AMFUser, String>)AMFUser::setMobilePhone);
		attributeGetterFunctions.put("address", AMFUser::getAddress);
		attributeSetterBiConsumers.put(
			"address", (BiConsumer<AMFUser, String>)AMFUser::setAddress);
		attributeGetterFunctions.put("address2", AMFUser::getAddress2);
		attributeSetterBiConsumers.put(
			"address2", (BiConsumer<AMFUser, String>)AMFUser::setAddress2);
		attributeGetterFunctions.put("city", AMFUser::getCity);
		attributeSetterBiConsumers.put(
			"city", (BiConsumer<AMFUser, String>)AMFUser::setCity);
		attributeGetterFunctions.put("state", AMFUser::getState);
		attributeSetterBiConsumers.put(
			"state", (BiConsumer<AMFUser, String>)AMFUser::setState);
		attributeGetterFunctions.put("zip", AMFUser::getZip);
		attributeSetterBiConsumers.put(
			"zip", (BiConsumer<AMFUser, String>)AMFUser::setZip);
		attributeGetterFunctions.put(
			"securityQuestion", AMFUser::getSecurityQuestion);
		attributeSetterBiConsumers.put(
			"securityQuestion",
			(BiConsumer<AMFUser, String>)AMFUser::setSecurityQuestion);
		attributeGetterFunctions.put(
			"securityAnswer", AMFUser::getSecurityAnswer);
		attributeSetterBiConsumers.put(
			"securityAnswer",
			(BiConsumer<AMFUser, String>)AMFUser::setSecurityAnswer);
		attributeGetterFunctions.put("acceptedTou", AMFUser::getAcceptedTou);
		attributeSetterBiConsumers.put(
			"acceptedTou",
			(BiConsumer<AMFUser, String>)AMFUser::setAcceptedTou);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAmfUserId() {
		return _amfUserId;
	}

	@Override
	public void setAmfUserId(long amfUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amfUserId = amfUserId;
	}

	@Override
	public String getAmfUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getAmfUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setAmfUserUuid(String amfUserUuid) {
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstName = firstName;
	}

	@JSON
	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastName = lastName;
	}

	@JSON
	@Override
	public String getEmailAddress() {
		if (_emailAddress == null) {
			return "";
		}
		else {
			return _emailAddress;
		}
	}

	@Override
	public void setEmailAddress(String emailAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_emailAddress = emailAddress;
	}

	@JSON
	@Override
	public String getGender() {
		if (_gender == null) {
			return "";
		}
		else {
			return _gender;
		}
	}

	@Override
	public void setGender(String gender) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gender = gender;
	}

	@JSON
	@Override
	public String getBirthDay() {
		if (_birthDay == null) {
			return "";
		}
		else {
			return _birthDay;
		}
	}

	@Override
	public void setBirthDay(String birthDay) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_birthDay = birthDay;
	}

	@JSON
	@Override
	public String getBirthMonth() {
		if (_birthMonth == null) {
			return "";
		}
		else {
			return _birthMonth;
		}
	}

	@Override
	public void setBirthMonth(String birthMonth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_birthMonth = birthMonth;
	}

	@JSON
	@Override
	public String getBirthYear() {
		if (_birthYear == null) {
			return "";
		}
		else {
			return _birthYear;
		}
	}

	@Override
	public void setBirthYear(String birthYear) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_birthYear = birthYear;
	}

	@JSON
	@Override
	public String getPassword() {
		if (_password == null) {
			return "";
		}
		else {
			return _password;
		}
	}

	@Override
	public void setPassword(String password) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_password = password;
	}

	@JSON
	@Override
	public String getConfirmedPassword() {
		if (_confirmedPassword == null) {
			return "";
		}
		else {
			return _confirmedPassword;
		}
	}

	@Override
	public void setConfirmedPassword(String confirmedPassword) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_confirmedPassword = confirmedPassword;
	}

	@JSON
	@Override
	public String getHomePhone() {
		if (_homePhone == null) {
			return "";
		}
		else {
			return _homePhone;
		}
	}

	@Override
	public void setHomePhone(String homePhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_homePhone = homePhone;
	}

	@JSON
	@Override
	public String getMobilePhone() {
		if (_mobilePhone == null) {
			return "";
		}
		else {
			return _mobilePhone;
		}
	}

	@Override
	public void setMobilePhone(String mobilePhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mobilePhone = mobilePhone;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return "";
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address = address;
	}

	@JSON
	@Override
	public String getAddress2() {
		if (_address2 == null) {
			return "";
		}
		else {
			return _address2;
		}
	}

	@Override
	public void setAddress2(String address2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address2 = address2;
	}

	@JSON
	@Override
	public String getCity() {
		if (_city == null) {
			return "";
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_city = city;
	}

	@JSON
	@Override
	public String getState() {
		if (_state == null) {
			return "";
		}
		else {
			return _state;
		}
	}

	@Override
	public void setState(String state) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_state = state;
	}

	@JSON
	@Override
	public String getZip() {
		if (_zip == null) {
			return "";
		}
		else {
			return _zip;
		}
	}

	@Override
	public void setZip(String zip) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_zip = zip;
	}

	@JSON
	@Override
	public String getSecurityQuestion() {
		if (_securityQuestion == null) {
			return "";
		}
		else {
			return _securityQuestion;
		}
	}

	@Override
	public void setSecurityQuestion(String securityQuestion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_securityQuestion = securityQuestion;
	}

	@JSON
	@Override
	public String getSecurityAnswer() {
		if (_securityAnswer == null) {
			return "";
		}
		else {
			return _securityAnswer;
		}
	}

	@Override
	public void setSecurityAnswer(String securityAnswer) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_securityAnswer = securityAnswer;
	}

	@JSON
	@Override
	public String getAcceptedTou() {
		if (_acceptedTou == null) {
			return "";
		}
		else {
			return _acceptedTou;
		}
	}

	@Override
	public void setAcceptedTou(String acceptedTou) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_acceptedTou = acceptedTou;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(AMFUser.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AMFUser.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AMFUser toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AMFUser>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AMFUserImpl amfUserImpl = new AMFUserImpl();

		amfUserImpl.setUuid(getUuid());
		amfUserImpl.setAmfUserId(getAmfUserId());
		amfUserImpl.setGroupId(getGroupId());
		amfUserImpl.setCompanyId(getCompanyId());
		amfUserImpl.setUserId(getUserId());
		amfUserImpl.setUserName(getUserName());
		amfUserImpl.setCreateDate(getCreateDate());
		amfUserImpl.setModifiedDate(getModifiedDate());
		amfUserImpl.setFirstName(getFirstName());
		amfUserImpl.setLastName(getLastName());
		amfUserImpl.setEmailAddress(getEmailAddress());
		amfUserImpl.setGender(getGender());
		amfUserImpl.setBirthDay(getBirthDay());
		amfUserImpl.setBirthMonth(getBirthMonth());
		amfUserImpl.setBirthYear(getBirthYear());
		amfUserImpl.setPassword(getPassword());
		amfUserImpl.setConfirmedPassword(getConfirmedPassword());
		amfUserImpl.setHomePhone(getHomePhone());
		amfUserImpl.setMobilePhone(getMobilePhone());
		amfUserImpl.setAddress(getAddress());
		amfUserImpl.setAddress2(getAddress2());
		amfUserImpl.setCity(getCity());
		amfUserImpl.setState(getState());
		amfUserImpl.setZip(getZip());
		amfUserImpl.setSecurityQuestion(getSecurityQuestion());
		amfUserImpl.setSecurityAnswer(getSecurityAnswer());
		amfUserImpl.setAcceptedTou(getAcceptedTou());

		amfUserImpl.resetOriginalValues();

		return amfUserImpl;
	}

	@Override
	public int compareTo(AMFUser amfUser) {
		int value = 0;

		value = getFirstName().compareTo(amfUser.getFirstName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AMFUser)) {
			return false;
		}

		AMFUser amfUser = (AMFUser)object;

		long primaryKey = amfUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AMFUser> toCacheModel() {
		AMFUserCacheModel amfUserCacheModel = new AMFUserCacheModel();

		amfUserCacheModel.uuid = getUuid();

		String uuid = amfUserCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			amfUserCacheModel.uuid = null;
		}

		amfUserCacheModel.amfUserId = getAmfUserId();

		amfUserCacheModel.groupId = getGroupId();

		amfUserCacheModel.companyId = getCompanyId();

		amfUserCacheModel.userId = getUserId();

		amfUserCacheModel.userName = getUserName();

		String userName = amfUserCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			amfUserCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			amfUserCacheModel.createDate = createDate.getTime();
		}
		else {
			amfUserCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			amfUserCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			amfUserCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		amfUserCacheModel.firstName = getFirstName();

		String firstName = amfUserCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			amfUserCacheModel.firstName = null;
		}

		amfUserCacheModel.lastName = getLastName();

		String lastName = amfUserCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			amfUserCacheModel.lastName = null;
		}

		amfUserCacheModel.emailAddress = getEmailAddress();

		String emailAddress = amfUserCacheModel.emailAddress;

		if ((emailAddress != null) && (emailAddress.length() == 0)) {
			amfUserCacheModel.emailAddress = null;
		}

		amfUserCacheModel.gender = getGender();

		String gender = amfUserCacheModel.gender;

		if ((gender != null) && (gender.length() == 0)) {
			amfUserCacheModel.gender = null;
		}

		amfUserCacheModel.birthDay = getBirthDay();

		String birthDay = amfUserCacheModel.birthDay;

		if ((birthDay != null) && (birthDay.length() == 0)) {
			amfUserCacheModel.birthDay = null;
		}

		amfUserCacheModel.birthMonth = getBirthMonth();

		String birthMonth = amfUserCacheModel.birthMonth;

		if ((birthMonth != null) && (birthMonth.length() == 0)) {
			amfUserCacheModel.birthMonth = null;
		}

		amfUserCacheModel.birthYear = getBirthYear();

		String birthYear = amfUserCacheModel.birthYear;

		if ((birthYear != null) && (birthYear.length() == 0)) {
			amfUserCacheModel.birthYear = null;
		}

		amfUserCacheModel.password = getPassword();

		String password = amfUserCacheModel.password;

		if ((password != null) && (password.length() == 0)) {
			amfUserCacheModel.password = null;
		}

		amfUserCacheModel.confirmedPassword = getConfirmedPassword();

		String confirmedPassword = amfUserCacheModel.confirmedPassword;

		if ((confirmedPassword != null) && (confirmedPassword.length() == 0)) {
			amfUserCacheModel.confirmedPassword = null;
		}

		amfUserCacheModel.homePhone = getHomePhone();

		String homePhone = amfUserCacheModel.homePhone;

		if ((homePhone != null) && (homePhone.length() == 0)) {
			amfUserCacheModel.homePhone = null;
		}

		amfUserCacheModel.mobilePhone = getMobilePhone();

		String mobilePhone = amfUserCacheModel.mobilePhone;

		if ((mobilePhone != null) && (mobilePhone.length() == 0)) {
			amfUserCacheModel.mobilePhone = null;
		}

		amfUserCacheModel.address = getAddress();

		String address = amfUserCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			amfUserCacheModel.address = null;
		}

		amfUserCacheModel.address2 = getAddress2();

		String address2 = amfUserCacheModel.address2;

		if ((address2 != null) && (address2.length() == 0)) {
			amfUserCacheModel.address2 = null;
		}

		amfUserCacheModel.city = getCity();

		String city = amfUserCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			amfUserCacheModel.city = null;
		}

		amfUserCacheModel.state = getState();

		String state = amfUserCacheModel.state;

		if ((state != null) && (state.length() == 0)) {
			amfUserCacheModel.state = null;
		}

		amfUserCacheModel.zip = getZip();

		String zip = amfUserCacheModel.zip;

		if ((zip != null) && (zip.length() == 0)) {
			amfUserCacheModel.zip = null;
		}

		amfUserCacheModel.securityQuestion = getSecurityQuestion();

		String securityQuestion = amfUserCacheModel.securityQuestion;

		if ((securityQuestion != null) && (securityQuestion.length() == 0)) {
			amfUserCacheModel.securityQuestion = null;
		}

		amfUserCacheModel.securityAnswer = getSecurityAnswer();

		String securityAnswer = amfUserCacheModel.securityAnswer;

		if ((securityAnswer != null) && (securityAnswer.length() == 0)) {
			amfUserCacheModel.securityAnswer = null;
		}

		amfUserCacheModel.acceptedTou = getAcceptedTou();

		String acceptedTou = amfUserCacheModel.acceptedTou;

		if ((acceptedTou != null) && (acceptedTou.length() == 0)) {
			amfUserCacheModel.acceptedTou = null;
		}

		return amfUserCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AMFUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AMFUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AMFUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((AMFUser)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AMFUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AMFUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AMFUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AMFUser)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AMFUser>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _amfUserId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _firstName;
	private String _lastName;
	private String _emailAddress;
	private String _gender;
	private String _birthDay;
	private String _birthMonth;
	private String _birthYear;
	private String _password;
	private String _confirmedPassword;
	private String _homePhone;
	private String _mobilePhone;
	private String _address;
	private String _address2;
	private String _city;
	private String _state;
	private String _zip;
	private String _securityQuestion;
	private String _securityAnswer;
	private String _acceptedTou;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AMFUser, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AMFUser)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("amfUserId", _amfUserId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("firstName", _firstName);
		_columnOriginalValues.put("lastName", _lastName);
		_columnOriginalValues.put("emailAddress", _emailAddress);
		_columnOriginalValues.put("gender", _gender);
		_columnOriginalValues.put("birthDay", _birthDay);
		_columnOriginalValues.put("birthMonth", _birthMonth);
		_columnOriginalValues.put("birthYear", _birthYear);
		_columnOriginalValues.put("password_", _password);
		_columnOriginalValues.put("confirmedPassword", _confirmedPassword);
		_columnOriginalValues.put("homePhone", _homePhone);
		_columnOriginalValues.put("mobilePhone", _mobilePhone);
		_columnOriginalValues.put("address", _address);
		_columnOriginalValues.put("address2", _address2);
		_columnOriginalValues.put("city", _city);
		_columnOriginalValues.put("state_", _state);
		_columnOriginalValues.put("zip", _zip);
		_columnOriginalValues.put("securityQuestion", _securityQuestion);
		_columnOriginalValues.put("securityAnswer", _securityAnswer);
		_columnOriginalValues.put("acceptedTou", _acceptedTou);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("password_", "password");
		attributeNames.put("state_", "state");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("amfUserId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("firstName", 256L);

		columnBitmasks.put("lastName", 512L);

		columnBitmasks.put("emailAddress", 1024L);

		columnBitmasks.put("gender", 2048L);

		columnBitmasks.put("birthDay", 4096L);

		columnBitmasks.put("birthMonth", 8192L);

		columnBitmasks.put("birthYear", 16384L);

		columnBitmasks.put("password_", 32768L);

		columnBitmasks.put("confirmedPassword", 65536L);

		columnBitmasks.put("homePhone", 131072L);

		columnBitmasks.put("mobilePhone", 262144L);

		columnBitmasks.put("address", 524288L);

		columnBitmasks.put("address2", 1048576L);

		columnBitmasks.put("city", 2097152L);

		columnBitmasks.put("state_", 4194304L);

		columnBitmasks.put("zip", 8388608L);

		columnBitmasks.put("securityQuestion", 16777216L);

		columnBitmasks.put("securityAnswer", 33554432L);

		columnBitmasks.put("acceptedTou", 67108864L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AMFUser _escapedModel;

}