/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AMFUser service. Represents a row in the &quot;AMFUser_AMFUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.amf.registration.model.impl.AMFUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.amf.registration.model.impl.AMFUserImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AMFUser
 * @generated
 */
@ProviderType
public interface AMFUserModel
	extends BaseModel<AMFUser>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a amf user model instance should use the {@link AMFUser} interface instead.
	 */

	/**
	 * Returns the primary key of this amf user.
	 *
	 * @return the primary key of this amf user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this amf user.
	 *
	 * @param primaryKey the primary key of this amf user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this amf user.
	 *
	 * @return the uuid of this amf user
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this amf user.
	 *
	 * @param uuid the uuid of this amf user
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the amf user ID of this amf user.
	 *
	 * @return the amf user ID of this amf user
	 */
	public long getAmfUserId();

	/**
	 * Sets the amf user ID of this amf user.
	 *
	 * @param amfUserId the amf user ID of this amf user
	 */
	public void setAmfUserId(long amfUserId);

	/**
	 * Returns the amf user uuid of this amf user.
	 *
	 * @return the amf user uuid of this amf user
	 */
	public String getAmfUserUuid();

	/**
	 * Sets the amf user uuid of this amf user.
	 *
	 * @param amfUserUuid the amf user uuid of this amf user
	 */
	public void setAmfUserUuid(String amfUserUuid);

	/**
	 * Returns the group ID of this amf user.
	 *
	 * @return the group ID of this amf user
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this amf user.
	 *
	 * @param groupId the group ID of this amf user
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this amf user.
	 *
	 * @return the company ID of this amf user
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this amf user.
	 *
	 * @param companyId the company ID of this amf user
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this amf user.
	 *
	 * @return the user ID of this amf user
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this amf user.
	 *
	 * @param userId the user ID of this amf user
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this amf user.
	 *
	 * @return the user uuid of this amf user
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this amf user.
	 *
	 * @param userUuid the user uuid of this amf user
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this amf user.
	 *
	 * @return the user name of this amf user
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this amf user.
	 *
	 * @param userName the user name of this amf user
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this amf user.
	 *
	 * @return the create date of this amf user
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this amf user.
	 *
	 * @param createDate the create date of this amf user
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this amf user.
	 *
	 * @return the modified date of this amf user
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this amf user.
	 *
	 * @param modifiedDate the modified date of this amf user
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this amf user.
	 *
	 * @return the first name of this amf user
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this amf user.
	 *
	 * @param firstName the first name of this amf user
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this amf user.
	 *
	 * @return the last name of this amf user
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this amf user.
	 *
	 * @param lastName the last name of this amf user
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the email address of this amf user.
	 *
	 * @return the email address of this amf user
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this amf user.
	 *
	 * @param emailAddress the email address of this amf user
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the gender of this amf user.
	 *
	 * @return the gender of this amf user
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this amf user.
	 *
	 * @param gender the gender of this amf user
	 */
	public void setGender(String gender);

	/**
	 * Returns the birth day of this amf user.
	 *
	 * @return the birth day of this amf user
	 */
	@AutoEscape
	public String getBirthDay();

	/**
	 * Sets the birth day of this amf user.
	 *
	 * @param birthDay the birth day of this amf user
	 */
	public void setBirthDay(String birthDay);

	/**
	 * Returns the birth month of this amf user.
	 *
	 * @return the birth month of this amf user
	 */
	@AutoEscape
	public String getBirthMonth();

	/**
	 * Sets the birth month of this amf user.
	 *
	 * @param birthMonth the birth month of this amf user
	 */
	public void setBirthMonth(String birthMonth);

	/**
	 * Returns the birth year of this amf user.
	 *
	 * @return the birth year of this amf user
	 */
	@AutoEscape
	public String getBirthYear();

	/**
	 * Sets the birth year of this amf user.
	 *
	 * @param birthYear the birth year of this amf user
	 */
	public void setBirthYear(String birthYear);

	/**
	 * Returns the password of this amf user.
	 *
	 * @return the password of this amf user
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this amf user.
	 *
	 * @param password the password of this amf user
	 */
	public void setPassword(String password);

	/**
	 * Returns the confirmed password of this amf user.
	 *
	 * @return the confirmed password of this amf user
	 */
	@AutoEscape
	public String getConfirmedPassword();

	/**
	 * Sets the confirmed password of this amf user.
	 *
	 * @param confirmedPassword the confirmed password of this amf user
	 */
	public void setConfirmedPassword(String confirmedPassword);

	/**
	 * Returns the home phone of this amf user.
	 *
	 * @return the home phone of this amf user
	 */
	@AutoEscape
	public String getHomePhone();

	/**
	 * Sets the home phone of this amf user.
	 *
	 * @param homePhone the home phone of this amf user
	 */
	public void setHomePhone(String homePhone);

	/**
	 * Returns the mobile phone of this amf user.
	 *
	 * @return the mobile phone of this amf user
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this amf user.
	 *
	 * @param mobilePhone the mobile phone of this amf user
	 */
	public void setMobilePhone(String mobilePhone);

	/**
	 * Returns the address of this amf user.
	 *
	 * @return the address of this amf user
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this amf user.
	 *
	 * @param address the address of this amf user
	 */
	public void setAddress(String address);

	/**
	 * Returns the address2 of this amf user.
	 *
	 * @return the address2 of this amf user
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this amf user.
	 *
	 * @param address2 the address2 of this amf user
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the city of this amf user.
	 *
	 * @return the city of this amf user
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this amf user.
	 *
	 * @param city the city of this amf user
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this amf user.
	 *
	 * @return the state of this amf user
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this amf user.
	 *
	 * @param state the state of this amf user
	 */
	public void setState(String state);

	/**
	 * Returns the zip of this amf user.
	 *
	 * @return the zip of this amf user
	 */
	@AutoEscape
	public String getZip();

	/**
	 * Sets the zip of this amf user.
	 *
	 * @param zip the zip of this amf user
	 */
	public void setZip(String zip);

	/**
	 * Returns the security question of this amf user.
	 *
	 * @return the security question of this amf user
	 */
	@AutoEscape
	public String getSecurityQuestion();

	/**
	 * Sets the security question of this amf user.
	 *
	 * @param securityQuestion the security question of this amf user
	 */
	public void setSecurityQuestion(String securityQuestion);

	/**
	 * Returns the security answer of this amf user.
	 *
	 * @return the security answer of this amf user
	 */
	@AutoEscape
	public String getSecurityAnswer();

	/**
	 * Sets the security answer of this amf user.
	 *
	 * @param securityAnswer the security answer of this amf user
	 */
	public void setSecurityAnswer(String securityAnswer);

	/**
	 * Returns the accepted tou of this amf user.
	 *
	 * @return the accepted tou of this amf user
	 */
	@AutoEscape
	public String getAcceptedTou();

	/**
	 * Sets the accepted tou of this amf user.
	 *
	 * @param acceptedTou the accepted tou of this amf user
	 */
	public void setAcceptedTou(String acceptedTou);

}